### PR TITLE
File - Responsivity - Device Type Extensions

### PR DESCRIPTION
**Pull request by desxz**
- FileType Extension Added to Find File Type Easyly
- Screen Size Check Added on Context
- Device OS Check Added on Context
- FileType Extension Tested
- Password Regex Added (Most Used)
- Some Packages Updated

### CODE REVIEW

**Review by VB10 — COMMENTED** [review]
super! @desxz thank u so much your contribution, i want to need one more thing. Could you update read me documentation about file, device type ?

**Comment by desxz** [comment]
Readme Updated

**Comment by desxz** [comment]
Readme updated file, responsivity and device type extensions.

**Comment by VB10** [comment]
supoeerr thank u, it's merged

**Pull request merged**
